# -*- coding: utf-8 -*-
"""Quantum algorithms — one robust page each (what it does, gate-level idea,
complexity, where it's used, Qiskit sketch)."""
CAT="quantum-algorithms"

A = {
 "grovers-algorithm": dict(title="Grover's Algorithm",
   lede="Grover's algorithm finds a marked item in an unsorted database of N entries in about √N steps — a quadratic speedup over any classical search.",
   facts=[("Speedup","quadratic — O(√N) vs O(N)"),("Primitives","oracle + diffusion"),("Optimal?","provably optimal for unstructured search")],
   what="Grover amplifies the amplitude of the solution state. Start in a uniform superposition (a layer of Hadamards), then repeat ~(π/4)√N times: apply an oracle that flips the phase of the marked state, then the diffusion operator that reflects all amplitudes about their mean. Each iteration rotates the state vector toward the answer.",
   circ={"qubits":3,"cols":[[{"g":"H","t":0}],[{"g":"H","t":1}],[{"g":"H","t":2}]]},
   steps=["Uniform superposition over all N = 2ⁿ states (Hadamards).","Oracle marks the solution by flipping its phase.","Diffusion reflects amplitudes about the mean, growing the marked amplitude.","Repeat ~(π/4)√N times, then measure."],
   uses="Unstructured search, and as a subroutine inside optimization, SAT solving, and mean/median estimation. The quadratic speedup is modest but very general.",
   code="from qiskit import QuantumCircuit\n# 3-qubit Grover skeleton\nqc = QuantumCircuit(3)\nqc.h(range(3))          # uniform superposition\n# ... oracle (phase-flip marked state) ...\n# ... diffusion operator ...\nqc.measure_all()",
   related=[("amplitude-amplification","Amplitude amplification"),("hadamard-gate","Hadamard"),("quantum-oracle","Oracles")]),
 "shors-algorithm": dict(title="Shor's Algorithm",
   lede="Shor's algorithm factors large integers in polynomial time — the result that put quantum computing on the map and threatens RSA encryption.",
   facts=[("Speedup","exponential over best-known classical"),("Core","quantum period-finding via QFT"),("Impact","breaks RSA / ECC at scale")],
   what="Factoring reduces to finding the period of the function f(x)=aˣ mod N. Shor prepares a superposition over x, computes aˣ mod N into a register (reversible modular exponentiation built from Toffoli-based arithmetic), then applies the quantum Fourier transform to read off the period. Classical post-processing (continued fractions) turns the period into a factor.",
   steps=["Pick random a; classically check gcd(a,N).","Quantum period-finding: superposition → modular exponentiation → QFT → measure.","Continued-fraction expansion recovers the period r.","Factors from gcd(a^{r/2} ± 1, N)."],
   uses="Integer factoring and discrete logarithms — hence its cryptographic significance and the driver behind post-quantum cryptography standards.",
   code="# Shor uses period-finding; conceptually:\n# 1) modular exponentiation into a register (Toffoli arithmetic)\n# 2) inverse QFT\n# 3) measure, continued fractions -> period -> factor",
   related=[("quantum-fourier-transform","QFT"),("quantum-phase-estimation","Phase estimation"),("toffoli-gate","Toffoli"),("post-quantum-cryptography","Post-quantum crypto")]),
 "deutsch-jozsa-algorithm": dict(title="Deutsch–Jozsa Algorithm",
   lede="Deutsch–Jozsa decides whether a black-box function is constant or balanced in a single query — the first clean, exponential quantum-classical separation.",
   facts=[("Queries","1 (quantum) vs up to 2ⁿ⁻¹+1 (classical, exact)"),("Type","exact, oracle-based"),("Role","teaching example of phase kickback")],
   what="Put the input register in superposition and the output qubit in |−⟩. The oracle writes f(x) as a phase (phase kickback). A final Hadamard layer interferes the amplitudes so that measuring all zeros means 'constant' and anything else means 'balanced' — decided in one query.",
   circ={"qubits":3,"cols":[[{"g":"H","t":0}],[{"g":"H","t":1}],[{"g":"H","t":2}]]},
   steps=["Input register in superposition; ancilla in |−⟩.","Oracle applies f via phase kickback.","Hadamard the input register.","Measure: all-zero ⇒ constant, else balanced."],
   uses="Mostly pedagogical, but the phase-kickback + interference pattern is the template for Bernstein–Vazirani, Simon, and Grover's oracle.",
   code="qc = QuantumCircuit(4,3)\nqc.x(3); qc.h(range(4))   # ancilla in |->, all in superposition\n# oracle U_f\nqc.h(range(3)); qc.measure(range(3),range(3))",
   related=[("bernstein-vazirani-algorithm","Bernstein–Vazirani"),("quantum-phase-kickback","Phase kickback"),("simons-algorithm","Simon")]),
 "bernstein-vazirani-algorithm": dict(title="Bernstein–Vazirani Algorithm",
   lede="Bernstein–Vazirani recovers a hidden bit-string s from a single query to a linear oracle — a full n-bit answer where classical needs n queries.",
   facts=[("Queries","1 vs n classical"),("Oracle","f(x)=s·x mod 2"),("Mechanism","phase kickback + interference")],
   what="With the input in superposition and the oracle encoding s·x as a phase, a final Hadamard layer maps the state directly to |s⟩ — the hidden string appears in the measurement outcome in one shot.",
   steps=["Superpose input; ancilla in |−⟩.","Oracle imprints s·x as phase.","Hadamard the input register.","Measure — the result is exactly s."],
   uses="A crisp demonstration that quantum interference can extract global structure in one query; a building block intuition for learning-from-oracle problems.",
   code="qc = QuantumCircuit(n+1,n)\nqc.x(n); qc.h(range(n+1))\n# oracle: CX from each i where s_i=1 to ancilla\nqc.h(range(n)); qc.measure(range(n),range(n))",
   related=[("deutsch-jozsa-algorithm","Deutsch–Jozsa"),("quantum-phase-kickback","Phase kickback")]),
 "simons-algorithm": dict(title="Simon's Algorithm",
   lede="Simon's algorithm finds a hidden period of a 2-to-1 function exponentially faster than any classical method — the direct inspiration for Shor.",
   facts=[("Speedup","exponential (oracle model)"),("Output","hidden string s via linear system"),("Legacy","blueprint for Shor's period-finding")],
   what="Simon's problem: f(x)=f(x⊕s). Each run yields a random bit-string y orthogonal to s. After ~n runs, solve the linear system over GF(2) to recover s. It was the first problem with a proven exponential quantum speedup in the query model.",
   uses="Historically pivotal — it showed exponential separation and led Shor to reframe factoring as period-finding.",
   code="# Repeat: prepare, apply oracle, Hadamard, measure -> y with y.s=0\n# Solve linear system over GF(2) for s",
   related=[("shors-algorithm","Shor"),("quantum-fourier-transform","QFT")]),
 "quantum-fourier-transform": dict(title="Quantum Fourier Transform (QFT)",
   lede="The QFT is the quantum analogue of the discrete Fourier transform — implemented in O(n²) gates instead of O(n2ⁿ), it is the engine inside Shor and phase estimation.",
   facts=[("Gates","O(n²) — H + controlled-phase"),("Classical DFT","O(N log N)"),("Role","period/phase extraction")],
   what="The QFT maps computational basis states to Fourier basis states using a ladder of Hadamards and controlled-phase rotations, followed by qubit-order reversal (swaps). It never gives you the amplitudes directly, but it concentrates periodic structure into measurable peaks.",
   circ={"qubits":3,"cols":[[{"g":"H","t":0}],[{"g":"P","c":1,"t":0}],[{"g":"H","t":1}]]},
   uses="Period-finding (Shor), phase estimation, and any algorithm that exploits periodicity or convolution structure.",
   code="from qiskit.circuit.library import QFT\nqc = QFT(num_qubits=3)",
   related=[("shors-algorithm","Shor"),("quantum-phase-estimation","Phase estimation"),("phase-gate","Phase gate")]),
 "quantum-phase-estimation": dict(title="Quantum Phase Estimation (QPE)",
   lede="Phase estimation reads the eigenphase of a unitary onto a register of qubits — the workhorse subroutine behind Shor, HHL, and quantum chemistry.",
   facts=[("Output","θ where U|ψ⟩=e^{2πiθ}|ψ⟩"),("Core","controlled-U powers + inverse QFT"),("Precision","one bit per counting qubit")],
   what="Controlled applications of U, U², U⁴, … kick their phases onto a counting register in superposition; an inverse QFT then converts those phases into a binary number you can measure. More counting qubits buy more precision.",
   steps=["Counting register in superposition; eigenstate in the target.","Apply controlled-U^{2ᵏ} for each counting qubit k.","Inverse QFT on the counting register.","Measure to read the phase."],
   uses="Eigenvalue estimation for chemistry and materials, order-finding in Shor, and matrix inversion in HHL.",
   code="# controlled-U^{2^k} ladder, then inverse QFT on counting register",
   related=[("quantum-fourier-transform","QFT"),("shors-algorithm","Shor"),("hhl-algorithm","HHL")]),
 "variational-quantum-eigensolver": dict(title="Variational Quantum Eigensolver (VQE)",
   lede="VQE finds the lowest energy of a quantum system using a hybrid loop — a parameterized quantum circuit tuned by a classical optimizer — and is a leading near-term algorithm.",
   facts=[("Type","hybrid quantum-classical, variational"),("Goal","ground-state energy"),("Hardware","NISQ-friendly (shallow ansatz)")],
   what="A parameterized ansatz circuit prepares a trial state; the quantum computer measures the expected energy ⟨ψ(θ)|H|ψ(θ)⟩; a classical optimizer updates θ to lower it. The variational principle guarantees the estimate never dips below the true ground-state energy.",
   circ={"qubits":2,"cols":[[{"g":"Ry","t":0}],[{"g":"Ry","t":1}],[{"g":"X","c":0,"t":1}]]},
   uses="Quantum chemistry, materials, and — relevant to Kronos — small-scale simulation of strongly-correlated systems where classical methods struggle.",
   code="from qiskit.circuit.library import TwoLocal\nansatz = TwoLocal(4,'ry','cx',reps=2)\n# classical optimizer minimizes <H> over ansatz parameters",
   related=[("qaoa","QAOA"),("ry-gate","Ry gate"),("quantum-simulation-overview","Quantum simulation")],
   gate="VQE quality is bounded by the ansatz and by measurement noise; on today's NISQ hardware results are promising but not yet beyond classical for large systems."),
 "qaoa": dict(title="QAOA (Quantum Approximate Optimization Algorithm)",
   lede="QAOA is a hybrid algorithm for combinatorial optimization — it alternates problem and mixing layers to approximate good solutions to hard discrete problems.",
   facts=[("Type","hybrid variational"),("Targets","MaxCut, scheduling, portfolio, routing"),("Depth","p layers trade quality for circuit depth")],
   what="Encode the objective as a cost Hamiltonian. QAOA alternates a cost-phase unitary and a mixing unitary p times, with 2p classical parameters optimized to maximize the expected objective. Higher p approaches the optimum but costs depth.",
   uses="Combinatorial optimization — a natural fit for logistics, scheduling, and design-space search problems.",
   code="from qiskit.circuit.library import QAOAAnsatz\n# build cost Hamiltonian, then optimize gamma/beta angles",
   related=[("variational-quantum-eigensolver","VQE"),("quantum-annealing","Quantum annealing"),("ising-model","Ising model")]),
 "hhl-algorithm": dict(title="HHL Algorithm (Quantum Linear Systems)",
   lede="HHL solves linear systems Ax=b with an exponential speedup in dimension — under conditions — by encoding the solution in a quantum state.",
   facts=[("Speedup","exponential in N (with caveats)"),("Core","phase estimation + controlled rotation"),("Caveat","state prep, condition number, readout limits")],
   what="HHL uses phase estimation to expose the eigenvalues of A, applies a controlled rotation to invert them, then uncomputes. The result is a quantum state proportional to x — great for computing ⟨x|M|x⟩-type quantities, less so if you need every component of x.",
   uses="Building block for quantum machine learning and differential-equation solvers; its caveats (sparse, well-conditioned A; efficient state prep) are as important as its promise.",
   code="# HHL: QPE(A) -> controlled 1/lambda rotation -> inverse QPE",
   related=[("quantum-phase-estimation","Phase estimation"),("quantum-machine-learning","Quantum ML")],
   gate="HHL's exponential speedup holds only under specific conditions; for many practical problems the caveats (state preparation, readout) erode the advantage."),
 "quantum-teleportation": dict(title="Quantum Teleportation",
   lede="Teleportation transfers an unknown qubit state using a shared entangled pair and two classical bits — no faster-than-light communication, but the backbone of quantum networks.",
   facts=[("Resource","1 Bell pair + 2 classical bits"),("Copies?","no — the original is destroyed (no-cloning)"),("Use","quantum networking, gate teleportation")],
   what="Alice entangles her unknown qubit with her half of a Bell pair via a CNOT and Hadamard, measures both, and sends the two classical outcomes to Bob, who applies X and/or Z corrections to recover the exact state on his half.",
   circ={"qubits":3,"cols":[[{"g":"X","c":0,"t":1}],[{"g":"H","t":0}],[{"g":"Z","c":0,"t":2}]]},
   uses="Quantum repeaters and networks, and 'gate teleportation' — a fault-tolerance technique for applying hard gates like T.",
   code="qc = QuantumCircuit(3,2)\nqc.h(1); qc.cx(1,2)   # Bell pair\nqc.cx(0,1); qc.h(0); qc.measure([0,1],[0,1])\n# Bob: apply X/Z conditioned on classical bits",
   related=[("bell-states","Bell states"),("superdense-coding","Superdense coding"),("no-cloning-theorem","No-cloning")]),
 "superdense-coding": dict(title="Superdense Coding",
   lede="Superdense coding sends two classical bits by transmitting a single qubit — the mirror image of teleportation, powered by shared entanglement.",
   facts=[("Ratio","2 classical bits per 1 qubit sent"),("Resource","1 pre-shared Bell pair"),("Dual of","teleportation")],
   what="Alice and Bob pre-share a Bell pair. Alice encodes two bits by applying one of {I, X, Z, XZ} to her qubit, then sends it to Bob, who undoes the entanglement and reads both bits.",
   uses="A conceptual cornerstone of quantum communication and a demonstration that entanglement is a usable resource.",
   code="# Alice: apply I/X/Z/XZ to encode 00/01/10/11\n# Bob: CX, H, measure both",
   related=[("quantum-teleportation","Teleportation"),("bell-states","Bell states"),("entanglement","Entanglement")]),
 "amplitude-amplification": dict(title="Amplitude Amplification",
   lede="Amplitude amplification is the generalization of Grover — it boosts the probability of any 'good' subspace quadratically, wrapping many algorithms in a speedup.",
   facts=[("Speedup","quadratic"),("Generalizes","Grover search"),("Pattern","reflect–reflect (oracle + about-mean)")],
   what="Given any procedure that produces a good outcome with probability p, amplitude amplification finds it in O(1/√p) repetitions instead of O(1/p), by alternating reflections about the good subspace and about the initial state.",
   uses="A meta-algorithm: speeds up Monte-Carlo estimation, search-within-search, and many quantum ML subroutines.",
   code="# generalized Grover: Q = -A S_0 A^{-1} S_f applied ~1/sqrt(p) times",
   related=[("grovers-algorithm","Grover"),("quantum-counting","Quantum counting")]),
 "quantum-annealing": dict(title="Quantum Annealing",
   lede="Quantum annealing seeks the ground state of an optimization problem by slowly evolving from an easy Hamiltonian to the problem Hamiltonian, using quantum tunnelling to escape local minima.",
   facts=[("Model","adiabatic / analog"),("Targets","QUBO / Ising problems"),("Contrast","gate-model QAOA is the digital cousin")],
   what="Start in the ground state of a simple transverse-field Hamiltonian, then adiabatically turn on the problem Hamiltonian. If done slowly enough, the system stays in the ground state — which now encodes the optimal solution. Tunnelling can cross barriers that trap classical annealers.",
   uses="Combinatorial optimization on specialized hardware; useful framing for design-space and scheduling problems.",
   code="# Map problem to Ising couplings J_ij, h_i; anneal transverse field -> 0",
   related=[("qaoa","QAOA"),("ising-model","Ising model"),("adiabatic-theorem","Adiabatic theorem")]),
 "quantum-walk": dict(title="Quantum Walks",
   lede="Quantum walks are the quantum analogue of random walks — they spread quadratically faster and underpin fast algorithms for search and graph problems.",
   facts=[("Spreading","ballistic (∝ t) vs diffusive (∝ √t)"),("Types","discrete-time & continuous-time"),("Uses","element distinctness, graph search")],
   what="Instead of a coin flip driving a classical step, a quantum walk keeps a superposition over positions that interfere, spreading much faster. Search algorithms built on quantum walks match or beat Grover on structured graphs.",
   uses="Element distinctness, spatial search, and a universal model of quantum computation in its own right.",
   code="# continuous-time: evolve exp(-iAt) with A the graph adjacency/Laplacian",
   related=[("grovers-algorithm","Grover"),("hamiltonian-simulation","Hamiltonian simulation")]),
 "quantum-phase-kickback": dict(title="Phase Kickback",
   lede="Phase kickback is the trick where a controlled operation pushes an eigenphase back onto the control qubit — the mechanism behind most quantum speedups.",
   facts=[("Where","Deutsch–Jozsa, BV, Grover oracle, QPE"),("Requires","target in an eigenstate of the operation")],
   what="If the target qubit is an eigenstate of the applied gate, a 'controlled' version doesn't change the target — instead the eigenphase appears as a relative phase on the control. Putting the target in |−⟩ turns an oracle's bit-answer into a phase the algorithm can interfere on.",
   uses="The conceptual key to oracle-based algorithms and phase estimation.",
   code="# ancilla in |->; controlled-U with U|->=-|-> flips control phase",
   related=[("deutsch-jozsa-algorithm","Deutsch–Jozsa"),("quantum-phase-estimation","Phase estimation")]),
 "quantum-counting": dict(title="Quantum Counting",
   lede="Quantum counting combines Grover's operator with phase estimation to count how many solutions exist — not just find one.",
   facts=[("Core","QPE on the Grover operator"),("Output","number of marked items M")],
   what="The Grover iteration is a rotation whose angle depends on the number of solutions. Running phase estimation on that operator reads the angle, and hence M, without enumerating solutions.",
   uses="Deciding satisfiability, estimating set sizes, and calibrating how many Grover iterations to run.",
   code="# QPE applied to the Grover diffusion*oracle operator",
   related=[("grovers-algorithm","Grover"),("quantum-phase-estimation","Phase estimation")]),
 "hamiltonian-simulation": dict(title="Hamiltonian Simulation",
   lede="Simulating how a quantum system evolves under its Hamiltonian is the original motivation for quantum computing — and where a fusion company's physics interest is sharpest.",
   facts=[("Goal","apply e^{-iHt}"),("Methods","Trotter, qubitization, LCU"),("Feynman","'simulate nature with a quantum machine'")],
   what="Time evolution e^{-iHt} is decomposed into implementable pieces — Trotter–Suzuki splitting for local Hamiltonians, or modern qubitization/LCU methods with near-optimal scaling. It lets a quantum computer model quantum dynamics that are exponentially hard classically.",
   uses="Quantum chemistry, materials, and — long term — strongly-correlated and kinetic plasma physics that resist classical simulation.",
   code="from qiskit.synthesis import SuzukiTrotter\n# Trotterize exp(-iHt) into gate layers",
   related=[("quantum-simulation-overview","Quantum simulation"),("variational-quantum-eigensolver","VQE"),("trotterization","Trotterization")],
   gate="Useful plasma-scale Hamiltonian simulation needs fault-tolerant hardware well beyond today's; Kronos treats it as a long-horizon capability, not a near-term tool."),
 "swap-test": dict(title="The SWAP Test",
   lede="The SWAP test estimates how similar two quantum states are — the overlap |⟨ψ|φ⟩|² — using a controlled-SWAP and a single measured qubit.",
   facts=[("Output","|⟨ψ|φ⟩|² from measurement statistics"),("Gate","controlled-SWAP (Fredkin)"),("Use","quantum kernels, fingerprinting")],
   what="An ancilla in superposition controls a SWAP between the two states; a Hadamard and measurement on the ancilla yield a 0-probability that encodes the overlap. It never reveals the states — only their similarity.",
   circ={"qubits":3,"cols":[[{"g":"H","t":0}],[{"g":"×","c":0,"t":1}],[{"g":"H","t":0}]]},
   uses="Quantum kernel methods and classifiers, state comparison, and entanglement diagnostics.",
   code="qc=QuantumCircuit(3,1)\nqc.h(0); qc.cswap(0,1,2); qc.h(0); qc.measure(0,0)",
   related=[("fredkin-gate","Fredkin"),("quantum-kernel-methods","Quantum kernels"),("quantum-machine-learning","Quantum ML")]),
}

def register(add,F):
    for slug,d in A.items():
        body=[("h2","What it does"),("p",d["what"])]
        if d.get("circ"): body+=[("h2","Circuit sketch"),("circuit",d["circ"])]
        if d.get("steps"): body+=[("h2","Steps"),("ul",d["steps"])]
        body+=[("h2","Where it's used"),("p",d["uses"]),
               ("h2","In code (Qiskit)"),("code",("python",d["code"]))]
        add(dict(slug=slug,title=d["title"],cat=CAT,lede=d["lede"],facts=d.get("facts"),
                 body=body,related=d["related"],gate=d.get("gate"),seo_type="TechArticle"))
